version: '3'
services:
  # redis database service (RECOMMENDED)
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./db:/data
    networks:
      - myhouse
    expose:
      - "6379"

  # myHouse core services
  myhouse:
    image: myhouseproject/myhouse:latest
    restart: always
    privileged: true
    depends_on:
      - redis
    volumes:
      - ./conf:/myHouse/conf
      - ./logs:/myHouse/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5m
      timeout: 10s
      retries: 3
    networks:
      - myhouse
    ports:
      - "80:80"

# Networks
networks:
  myhouse:
    driver: bridge
