version: '3'
services:
  # redis database service (RECOMMENDED)
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data
    networks:
      - myhouse
    expose:
      - "6379"

  # myHouse core services
  myhouse:
    image: myhouseproject/myhouse:latest
    restart: always
    privileged: true
    depends_on:
      - redis
    volumes:
      - ./conf:/conf
      - ./logs:/logs
    networks:
      - myhouse
    ports:
      - "80:80"

# Networks
networks:
  myhouse:
    driver: bridge
